FROM node

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

EXPOSE 4000

ENV MONGODB_USERNAME=root
ENV MONGODB_PASSWORD=secret
ENV MONGODB_URL=mongodb
ENV PORT=4000
ENV SESSION_SECRET=my-super-secret
ENV CLOUDINARY_CLOUD_NAME=dze0wnkeq
ENV CLOUDINARY_API_KEY=298619978454979
ENV CLOUDINARY_API_SECRET=VsyH9dZaqL3NFUKM6F1IWkZKxm0

CMD ["npm", "start"]